### ISSUE TITLE
plase  add install steps

### ISSUE THREAD

**Issue by vahidalvandi** [robsontenorio/laravel-docker#2]
hi
i want use this in production . i want use current laravel project with docker , and have many search and many repo but cant find complete instaltion way , like bellow tutotial , 
https://learn2torials.com/a/laravel8-production-docker-image

**Comment by robsontenorio** [comment]
Hi, 

There is no "install steps" because there are many ways to use docker images. Anyway the README offer some guidance for local running with `docker-compose`. I would not recommend `docker-compose` for production.

For production the only requirement is: `build the image and push to some private registry`. From there is up to you how to make it running.

I would recommend some infrastructure that make your life easier. For example, the company www.render.com does the work for you. But there are Rancher, Openshift and many other options.
